CREATE TABLE [dbo].[MOV]
(
    [Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    [TITLE] VARCHAR(60) NOT NULL, 
    [RELEASE] DATETIME NULL, 
    [PRICE] DECIMAL(18,2) NULL, 
    [GENRE] VARCHAR(30) NOT NULL, 
    [RATING] VARCHAR(5) NOT NULL
)
